### Send POST request with json body
POST https://localhost:5001/api/account/register
Content-Type: application/json

{
  "username": "joe",
  "gender": "Male",
  "password": "password"
}


###
GET https://localhost:5001/api/users

